version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/react-app/

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
