version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo Building the React app...
      - npm run build
      
  post_build:
    commands:
      - echo Packaging artifact...
      - mkdir -p output
      - cp -r dist output/build
      - cp appspec.yml output/appspec.yml
      - cp -r scripts output/scripts

artifacts:
  files:
    - '**/*'
  base-directory: output
  discard-paths: no
